import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from 'next/font/google'
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


const nunito = Nunito({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-nunito',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${nunito.variable} font-sans`}>
      <body>
      <main className='mx-auto flex min-h-screen flex-col flex-wrap gap-10 md:py-12 py-4 md:gap-16 px-12'>
            <Navbar />
            {children}
            <Footer />
          </main>
      </body>
    </html>
  );
}
